### ISSUE TITLE
Missing Texture

### ISSUE THREAD

**Issue by LiPingjiang** [DF-thangld/SketchupOulu#2]
It seem the problem is that the server cannot find the mtl file:

![untitled](https://cloud.githubusercontent.com/assets/11030498/13774542/3fd47218-eaa8-11e5-803c-ec0e215f17a1.png)

**Comment by DF-thangld** [comment]
Can you upload the whole file here? It seems with this file, I can get obj and mtl file but still cannot display it correctly
[LpzwUK0twDQavjNNZTu1D3uT23zZQppTbyEx6zZnydTjaoC0MH.zip](https://github.com/DF-thangld/SketchupOulu/files/173686/LpzwUK0twDQavjNNZTu1D3uT23zZQppTbyEx6zZnydTjaoC0MH.zip)

**Comment by LiPingjiang** [comment]
The mtl file has problems.
I use official website for testing, the material doesn't display either.
the code : https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_obj_mtl.html 
And the path of the mtl is correct, otherwise it will show error like 'cann't find the file' and stop working.
![untitled](https://cloud.githubusercontent.com/assets/11030498/13777044/3d778fce-eab6-11e5-9d50-08984d1fed75.png)

**Comment by LiPingjiang** [comment]
I am sure it is the wrong format of the mtl file they provided.
I try the official model provided by three js, it shows material successfully.
![untitled](https://cloud.githubusercontent.com/assets/11030498/13777157/eee0c6b8-eab6-11e5-87a8-f4eafc1a1423.png)

**Comment by DF-thangld** [comment]
Maybe you import it to blender, sketchup and see if it display correctly there?

**Comment by LiPingjiang** [comment]
Try other obj with mtl, also display correctly
![untitled](https://cloud.githubusercontent.com/assets/11030498/13777280/d44f4e7c-eab7-11e5-975c-4faab7e659ff.png)

**Comment by LiPingjiang** [comment]
It the wrong mtl's problem. I edit the model under blender and set red material and export again, it shows correctly. The code has no problems.

![untitled](https://cloud.githubusercontent.com/assets/11030498/13777630/0042496a-eaba-11e5-85f2-4dcbcc4551d3.png)

The problem is in the .mtl file:

`newmtl FrontColor`

`Ka 0.000000 0.000000 0.000000`
`Kd 1.000000 1.000000 1.000000`
`Ks 0.330000 0.330000 0.330000`
`newmtl Color_C16`
`Ka 0.000000 0.000000 0.000000`
`Kd 0.400000 0.200000 0.000000`
`Ks 0.330000 0.330000 0.330000`

 the "Kd 1.000000 1.000000 1.000000" means the rgb color of the diffuse color is 255,255,255, white, so the object is displayed correctly as the material is white.
